# ---------------------------------------------------------------------------
# File:   windows-release.yml
# Author: (c) 2026 Jens Kallup - paule32
# All rights reserved
#
# github.com CI workflow to create LOCALES.EXE for Windows 10/11 64-Bit Pro
# ---------------------------------------------------------------------------
name: Build Windows Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag, z. B. v0.0.1"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path src/requirements.txt) {
            pip install -r src/requirements.txt
          }

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --windowed `
            --name "locales" `
            --add-data "src/resources_rc.py;." `
            src/locales.py src/sysinfo.py src/theme

      - name: Package ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "dist/IIS-Setup/*" `
            -DestinationPath "Locales-${{ inputs.tag }}-windows.zip" `
            -Force

      - name: Create Git tag
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.tag }}
          name: Locales ${{ inputs.tag }}
          files: Locales-${{ inputs.tag }}-windows.zip
